site_name: Thebwt.com
theme: slate
pages:
        - Home: index.md
        - Work: work.md
        - Hobby: hobby.md
        - Guides:
                - Mumbles and Django-Mumble with Docker and Carina: mumble-carina-tutorial.md
